# Configuration file for ViT5-VQA project
# Defines dataset paths, model names, and training hyperparameters.

dataset:
  data_dir: data/openvivqa  # Path to prepared dataset directory (train.csv, val.csv, test.csv)

output:
  output_dir: vit5-vqa-results  # Directory to save checkpoints and logs

model:
  vit5_model: VietAI/vit5-base  # Name of the ViT5 model
  vit_model: google/vit-base-patch16-224-in21k  # Name of the ViT model

training:
  epochs: 3
  batch_size: 24
  gradient_accumulation_steps: 2
  learning_rate: 1e-4
  num_workers: 4
  eval_steps: 200
  save_steps: 200
  weight_decay: 0.01
  warmup_steps: 500
  logging_steps: 200
  generation_max_length: 128
  generation_num_beams: 2

evaluation:
  metrics:
    - bleu1
    - bleu2
    - bleu3
    - bleu4
    - meteor
    - rougeL
    - cider
